import type { SchemaResult } from '@/types/schema';
import type { Variant } from '@/types/journey';

/**
 * Emits a self-contained JavaScript converter for the fields the LLM
 * attributed to a UI operation.
 *
 * The file that comes out of here is meant to leave the app: drop it into a
 * pipeline, hand it a raw wpf/exe configuration, and get back the same compact
 * YAML this page shows. Everything it needs travels with it — the field list
 * is baked in as data at the top, so the interesting knob is right where you
 * will look for it.
 *
 * One deliberate difference from the page: the page collapses every array onto
 * a single representative element, because it is describing a shape. A
 * converter handed a real configuration keeps every element, because it is
 * describing that configuration.
 */

export function generateConverter(schema: SchemaResult, bundleName: string): string {
  const paths = [...schema.selected].sort();
  const perVariant = countByVariant(schema, paths);

  const list = paths.length
    ? paths.map((p) => '  ' + JSON.stringify(p) + ',').join('\n')
    : '  // No fields were attributed to a UI operation.';

  return `/**
 * UI-affected fields of "${escapeComment(bundleName)}" — generated by AFRA.
 *
 * Converts a raw wpf/exe configuration into YAML holding only the fields a
 * step's UI operation was found to drive. Ids, timestamps, derived counts and
 * environment settings are all dropped.
 *
 *   const { convert } = require('./converter');
 *   const yaml = convert(JSON.parse(fs.readFileSync('05.wpf.json', 'utf8')));
 *
 * Pass { emptyArrays: true } to blank out arrays of plain values, the way the
 * empty document does. Arrays of objects always keep their contents.
 */

/**
 * The fields to keep, written as paths in which '[]' stands for "any array
 * element" — so '/Devices/[]/Name' keeps the name of every device.
 *
 * ${paths.length} field${paths.length === 1 ? '' : 's'}: ${perVariant.both} in both variants, ${perVariant.wpf} only in wpf, ${perVariant.exe} only in exe.
 */
const UI_FIELDS = [
${list}
];

/** Returned by pick() for anything the field list does not ask for. */
const DROP = Symbol('drop');

function convert(config, options) {
  const emptyArrays = Boolean(options && options.emptyArrays);
  const kept = pick(config, index(UI_FIELDS));
  if (kept === DROP) return '{}\\n';
  return emit(kept, 0, emptyArrays).join('\\n') + '\\n';
}

/** The field list as a prefix tree, so one walk of the config does all the matching. */
function index(paths) {
  const root = node();
  for (const path of paths) {
    let cur = root;
    for (const seg of path.split('/').slice(1)) {
      let next = cur.children.get(seg);
      if (!next) {
        next = node();
        cur.children.set(seg, next);
      }
      cur = next;
    }
    cur.keep = true;
  }
  return root;
}

function node() {
  return { children: new Map(), keep: false };
}

/** Copy out of \`value\` only what \`spec\` names. */
function pick(value, spec) {
  if (!spec.children.size) return spec.keep ? value : DROP;

  if (Array.isArray(value)) {
    const element = spec.children.get('[]');
    if (!element) return spec.keep ? [] : DROP;
    const out = [];
    for (const item of value) {
      const got = pick(item, element);
      if (got !== DROP) out.push(got);
    }
    return out;
  }

  if (value !== null && typeof value === 'object') {
    const out = {};
    // Keys are visited in sorted order so the same input always produces
    // byte-identical output.
    for (const key of [...spec.children.keys()].sort()) {
      if (key === '[]' || !(key in value)) continue;
      const got = pick(value[key], spec.children.get(key));
      if (got !== DROP) out[key] = got;
    }
    if (Object.keys(out).length || spec.keep) return out;
    return DROP;
  }

  return spec.keep ? value : DROP;
}

function emit(value, depth, emptyArrays) {
  const out = [];
  if (Array.isArray(value)) emitSeq(value, depth, emptyArrays, out);
  else if (isObject(value)) emitMap(value, depth, emptyArrays, out);
  else out.push(indent(depth) + scalar(value));
  return out;
}

function emitMap(obj, depth, emptyArrays, out) {
  const keys = Object.keys(obj);
  if (!keys.length) {
    out.push(indent(depth) + '{}');
    return;
  }
  for (const k of keys) {
    const v = obj[k];
    if (Array.isArray(v)) {
      if (collapses(v, emptyArrays)) {
        out.push(indent(depth) + key(k) + ': []');
        continue;
      }
      out.push(indent(depth) + key(k) + ':');
      emitSeq(v, depth + 1, emptyArrays, out);
    } else if (isObject(v)) {
      if (!Object.keys(v).length) {
        out.push(indent(depth) + key(k) + ': {}');
        continue;
      }
      out.push(indent(depth) + key(k) + ':');
      emitMap(v, depth + 1, emptyArrays, out);
    } else {
      out.push(indent(depth) + key(k) + ': ' + scalar(v));
    }
  }
}

function emitSeq(arr, depth, emptyArrays, out) {
  for (const item of arr) {
    if (Array.isArray(item)) {
      if (collapses(item, emptyArrays)) {
        out.push(indent(depth) + '- []');
        continue;
      }
      out.push(indent(depth) + '-');
      emitSeq(item, depth + 1, emptyArrays, out);
    } else if (isObject(item)) {
      if (!Object.keys(item).length) {
        out.push(indent(depth) + '- {}');
        continue;
      }
      // YAML puts the dash on the same line as the element's first key.
      // Measured rather than assumed, so changing indent() stays safe.
      const at = out.length;
      emitMap(item, depth + 1, emptyArrays, out);
      out[at] = indent(depth) + '- ' + out[at].slice(indent(depth + 1).length);
    } else {
      out.push(indent(depth) + '- ' + scalar(item));
    }
  }
}

/**
 * Only arrays that directly hold plain values empty out — an array of objects
 * carries fields, and blanking it would delete them from the document.
 */
function collapses(arr, emptyArrays) {
  return !arr.length || (emptyArrays && isValue(arr[0]));
}

const RESERVED = /^(y|n|yes|no|true|false|on|off|null|~)$/i;
const NUMBERISH = /^[-+]?(\\d+\\.?\\d*|\\.\\d+)([eE][-+]?\\d+)?$/;
const AWKWARD = /[:#\\n\\r\\t"'\\\\{}[\\],&*!|>%@\`]|^[-?]|^\\s|\\s$/;

function scalar(v) {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') {
    return Number.isFinite(v) ? String(v) : JSON.stringify(String(v));
  }
  return quote(String(v));
}

function key(k) {
  return quote(k);
}

/** Plain YAML scalars are ambiguous often enough to be worth checking. */
function quote(s) {
  if (s === '') return '""';
  if (RESERVED.test(s) || NUMBERISH.test(s) || AWKWARD.test(s)) {
    // JSON string escaping is valid YAML double-quoted style.
    return JSON.stringify(s);
  }
  return s;
}

function indent(depth) {
  return '  '.repeat(depth);
}

function isValue(v) {
  return v === null || typeof v !== 'object';
}

function isObject(v) {
  return v !== null && typeof v === 'object' && !Array.isArray(v);
}

if (typeof module !== 'undefined') module.exports = { convert, UI_FIELDS };
`;
}

function countByVariant(
  schema: SchemaResult,
  paths: string[],
): Record<Variant | 'both', number> {
  const out = { wpf: 0, exe: 0, both: 0 };
  for (const p of paths) {
    const sources = schema.index.get(p)?.sources ?? [];
    const wpf = sources.some((s) => s.variant === 'wpf');
    const exe = sources.some((s) => s.variant === 'exe');
    if (wpf && exe) out.both++;
    else if (wpf) out.wpf++;
    else if (exe) out.exe++;
  }
  return out;
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, '*\\/');
}
