import type { SchemaResult } from '@/types/schema';
import type { Variant } from '@/types/journey';

/**
 * Emits a self-contained JavaScript converter for the fields the LLM
 * attributed to a UI operation.
 *
 * The file that comes out of here is meant to leave the app: drop it into a
 * pipeline, hand it a raw wpf/exe configuration, and get back the same compact
 * YAML this page shows. Everything it needs travels with it — the field list
 * is baked in as data at the top, so the interesting knob is right where you
 * will look for it.
 *
 * Semantics match the sample panes on the JSON-to-YML page:
 *   - keep every element of every array (a configuration, not a shape),
 *   - peel {"$values":[...]} and {"$type":"…","$value":X} wrappers,
 *   - drop $type/$id/$ref meta leaves from mixed objects,
 *   - fold repeated subtrees into YAML anchors (&d1) and aliases (*d1).
 */

export function generateConverter(schema: SchemaResult, bundleName: string): string {
  const paths = [...schema.selected].sort();
  const perVariant = countByVariant(schema, paths);

  const list = paths.length
    ? paths.map((p) => '  ' + JSON.stringify(p) + ',').join('\n')
    : '  // No fields were attributed to a UI operation.';

  return `/**
 * UI-affected fields of "${escapeComment(bundleName)}" — generated by AFRA.
 *
 * Converts a raw wpf/exe configuration into YAML holding only the fields a
 * step's UI operation was found to drive. Ids, timestamps, derived counts and
 * environment settings are all dropped.
 *
 *   const { convert } = require('./converter');
 *   const yaml = convert(JSON.parse(fs.readFileSync('05.wpf.json', 'utf8')));
 *
 * The output is compacted: {"\$values":[...]} wrappers unwrap to their arrays,
 * {"\$type":"…","\$value":X} wrappers unwrap to X, and framework meta keys
 * (\$type, \$id, \$ref) are dropped from mixed objects. Repeated subtrees are
 * emitted with YAML anchors (&d1) and aliases (*d1). Pass { dedupe: false }
 * to skip the anchor/alias pass and get a flat, fully-inlined document.
 */

/**
 * The fields to keep, written as paths in which '[]' stands for "any array
 * element" — so '/Devices/[]/Name' keeps the name of every device.
 *
 * ${paths.length} field${paths.length === 1 ? '' : 's'}: ${perVariant.both} in both variants, ${perVariant.wpf} only in wpf, ${perVariant.exe} only in exe.
 */
const UI_FIELDS = [
${list}
];

/** Returned by pick() for anything the field list does not ask for. */
const DROP = Symbol('drop');

function convert(config, options) {
  // Default ON: only disabled when the caller explicitly passes false. The
  // simpler \`options && options.dedupe !== false\` short-circuits to
  // \`undefined\` when \`options\` is absent, which is falsy — so aliasing
  // would silently never run unless the caller supplied an options object.
  const dedupe = !options || options.dedupe !== false;
  const kept = pick(config, index(UI_FIELDS));
  if (kept === DROP) return '{}\\n';
  const compacted = compact(kept);
  const anchors = dedupe ? detectDuplicates(compacted) : new Map();
  return emit(compacted, 0, anchors, new Set()).join('\\n') + '\\n';
}

/* ------------------------- Structural compaction ------------------------- */
// Mirrors the same rules the app applies to the sample YAML pane.

function compact(v) {
  if (Array.isArray(v)) return v.map(compact);
  if (!isObject(v)) return v;
  const keys = Object.keys(v);

  // { $values: [...] } → the array.
  if (keys.length === 1 && keys[0] === '$values' && Array.isArray(v.$values)) {
    return compact(v.$values);
  }
  // { $type, $value } where $value is a primitive → the primitive.
  if (
    keys.length === 2 && keys.includes('$type') && keys.includes('$value') &&
    isValue(v.$value)
  ) {
    return v.$value;
  }
  const out = {};
  for (const k of keys) {
    // Drop framework meta-key siblings from mixed objects.
    if ((k === '$type' || k === '$id' || k === '$ref') && keys.length > 1) continue;
    out[k] = compact(v[k]);
  }
  return out;
}

/* ------------------------- Duplicate detection --------------------------- */

/**
 * Walk the (already-compacted) tree and assign a stable anchor name to each
 * subtree that repeats, has at least 2 leaves, and appears at least twice.
 * Returns a Map keyed by object identity → anchor string. First-occurrence
 * detection during emit uses a separate "seen" set the caller passes in.
 */
function detectDuplicates(root) {
  const groups = new Map(); // hash -> Array<object identity>

  const visit = (n) => {
    if (Array.isArray(n)) {
      for (const it of n) visit(it);
      registerContainer(n);
    } else if (isObject(n)) {
      for (const k of Object.keys(n)) visit(n[k]);
      registerContainer(n);
    }
  };
  const registerContainer = (n) => {
    if (leafCount(n) < 2) return;
    const h = hashOf(n);
    const list = groups.get(h);
    if (list) list.push(n);
    else groups.set(h, [n]);
  };

  visit(root);

  const anchors = new Map();
  let counter = 0;
  for (const [, nodes] of groups) {
    if (nodes.length < 2) continue;
    counter++;
    const name = 'd' + counter;
    for (const n of nodes) anchors.set(n, name);
  }
  return anchors;
}

function leafCount(n) {
  if (Array.isArray(n)) return n.reduce((s, x) => s + leafCount(x), 0);
  if (isObject(n)) {
    let s = 0;
    for (const k of Object.keys(n)) s += leafCount(n[k]);
    return s;
  }
  return 1;
}

function hashOf(n) {
  if (Array.isArray(n)) return '[' + n.map(hashOf).join(',') + ']';
  if (isObject(n)) {
    return '{' + Object.keys(n).sort()
      .map((k) => JSON.stringify(k) + ':' + hashOf(n[k])).join(',') + '}';
  }
  if (n === null) return 'null';
  return typeof n + ':' + JSON.stringify(n);
}

/** The field list as a prefix tree, so one walk of the config does all the matching. */
function index(paths) {
  const root = node();
  for (const path of paths) {
    let cur = root;
    for (const seg of path.split('/').slice(1)) {
      let next = cur.children.get(seg);
      if (!next) {
        next = node();
        cur.children.set(seg, next);
      }
      cur = next;
    }
    cur.keep = true;
  }
  return root;
}

function node() {
  return { children: new Map(), keep: false };
}

/** Copy out of \`value\` only what \`spec\` names. */
function pick(value, spec) {
  if (!spec.children.size) return spec.keep ? value : DROP;

  if (Array.isArray(value)) {
    const element = spec.children.get('[]');
    if (!element) return spec.keep ? [] : DROP;
    const out = [];
    for (const item of value) {
      const got = pick(item, element);
      if (got !== DROP) out.push(got);
    }
    return out;
  }

  if (value !== null && typeof value === 'object') {
    const out = {};
    // Preserve source key order so the emitted YAML mirrors the input.
    for (const key of Object.keys(value)) {
      const childSpec = spec.children.get(key);
      if (!childSpec) continue;
      const got = pick(value[key], childSpec);
      if (got !== DROP) out[key] = got;
    }
    if (Object.keys(out).length || spec.keep) return out;
    return DROP;
  }

  return spec.keep ? value : DROP;
}

function emit(value, depth, anchors, seen) {
  const out = [];
  if (Array.isArray(value)) emitSeq(value, depth, out, anchors, seen);
  else if (isObject(value)) emitMap(value, depth, out, anchors, seen);
  else out.push(indent(depth) + scalar(value));
  return out;
}

function anchorTag(node, anchors, seen) {
  // Returns { alias?, anchor? } — alias means "reference only", anchor means
  // "define here". Callers can inline whichever marker they got.
  const name = anchors.get(node);
  if (!name) return {};
  if (seen.has(name)) return { alias: name };
  seen.add(name);
  return { anchor: name };
}

function emitMap(obj, depth, out, anchors, seen) {
  const keys = Object.keys(obj);
  if (!keys.length) {
    out.push(indent(depth) + '{}');
    return;
  }
  for (const k of keys) {
    const v = obj[k];
    const tag = isValue(v) ? {} : anchorTag(v, anchors, seen);
    if (tag.alias) {
      out.push(indent(depth) + key(k) + ': *' + tag.alias);
      continue;
    }
    const mark = tag.anchor ? ' &' + tag.anchor : '';
    if (Array.isArray(v)) {
      if (!v.length) {
        out.push(indent(depth) + key(k) + ':' + mark + ' []');
        continue;
      }
      out.push(indent(depth) + key(k) + ':' + mark);
      emitSeq(v, depth + 1, out, anchors, seen);
    } else if (isObject(v)) {
      if (!Object.keys(v).length) {
        out.push(indent(depth) + key(k) + ':' + mark + ' {}');
        continue;
      }
      out.push(indent(depth) + key(k) + ':' + mark);
      emitMap(v, depth + 1, out, anchors, seen);
    } else {
      out.push(indent(depth) + key(k) + ': ' + scalar(v));
    }
  }
}

function emitSeq(arr, depth, out, anchors, seen) {
  for (const item of arr) {
    const tag = isValue(item) ? {} : anchorTag(item, anchors, seen);
    if (tag.alias) {
      out.push(indent(depth) + '- *' + tag.alias);
      continue;
    }
    const mark = tag.anchor ? ' &' + tag.anchor : '';
    if (Array.isArray(item)) {
      if (!item.length) {
        out.push(indent(depth) + '-' + mark + ' []');
        continue;
      }
      out.push(indent(depth) + '-' + mark);
      emitSeq(item, depth + 1, out, anchors, seen);
    } else if (isObject(item)) {
      if (!Object.keys(item).length) {
        out.push(indent(depth) + '-' + mark + ' {}');
        continue;
      }
      // YAML puts the dash on the same line as the element's first key.
      const at = out.length;
      emitMap(item, depth + 1, out, anchors, seen);
      const head = indent(depth) + '- ' + (tag.anchor ? '&' + tag.anchor + ' ' : '') +
        out[at].slice(indent(depth + 1).length);
      out[at] = head;
    } else {
      out.push(indent(depth) + '- ' + scalar(item));
    }
  }
}

const RESERVED = /^(y|n|yes|no|true|false|on|off|null|~)$/i;
const NUMBERISH = /^[-+]?(\\d+\\.?\\d*|\\.\\d+)([eE][-+]?\\d+)?$/;
const AWKWARD = /[:#\\n\\r\\t"'\\\\{}[\\],&*!|>%@\`]|^[-?]|^\\s|\\s$/;

function scalar(v) {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') {
    return Number.isFinite(v) ? String(v) : JSON.stringify(String(v));
  }
  return quote(String(v));
}

function key(k) {
  return quote(k);
}

/** Plain YAML scalars are ambiguous often enough to be worth checking. */
function quote(s) {
  if (s === '') return '""';
  if (RESERVED.test(s) || NUMBERISH.test(s) || AWKWARD.test(s)) {
    // JSON string escaping is valid YAML double-quoted style.
    return JSON.stringify(s);
  }
  return s;
}

function indent(depth) {
  return '  '.repeat(depth);
}

function isValue(v) {
  return v === null || typeof v !== 'object';
}

function isObject(v) {
  return v !== null && typeof v === 'object' && !Array.isArray(v);
}

if (typeof module !== 'undefined') module.exports = { convert, UI_FIELDS };
`;
}

function countByVariant(
  schema: SchemaResult,
  paths: string[],
): Record<Variant | 'both', number> {
  const out = { wpf: 0, exe: 0, both: 0 };
  for (const p of paths) {
    const sources = schema.index.get(p)?.sources ?? [];
    const wpf = sources.some((s) => s.variant === 'wpf');
    const exe = sources.some((s) => s.variant === 'exe');
    if (wpf && exe) out.both++;
    else if (wpf) out.wpf++;
    else if (exe) out.exe++;
  }
  return out;
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, '*\\/');
}
